### ISSUE TITLE
Gadget images on ghcr.io are private

### ISSUE THREAD

**Issue by alban** [blanquicet/tcprst-gadget#1]
Hi @blanquicet,
It seems your images on ghcr.io are private, so only you can use them.

Please go to:
- https://github.com/users/blanquicet/packages/container/tcprst-gadget/settings
- https://github.com/users/blanquicet/packages/container/tcprst-gadget-without-nf/settings

And check "Change package visibility" at the bottom of the pages.

**Comment by blanquicet** [comment]
Done. Thanks!
